### ISSUE TITLE
[JENKINS-69875] Feature: abort job while performing scm checkout cause retry instead of aborting it

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/git-plugin#3759]
<p>If you increase  SCM checkout retry, and you abort a job while it performing scm checkout, it will not detect that the job has been aborted and it will <b>retry</b> the job instead of <b>aborting</b> it. see log:</p>

<pre>
Started by user BLABLA
Obtained Jenkinsfile from c123456789101112131415
[Pipeline] Start of Pipeline
[Pipeline] library
Loading library pipeline-library@​master
Attempting to resolve my-branch from remote references...
 > git --version # timeout=10
 > git --version # <span class="code-quote">'git version 2.30.2'</span>
using GIT_ASKPASS to set credentials 
 > git ls-remote -h -- https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git # timeout=10
</span>Found match: refs/heads/my-branch revision 164e4f446c6fb83a07a71f6f657c3ec1b5c35779
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential my-token
Wiping out workspace first.
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git
</span> > git init /<span class="code-keyword">var</span>/jenkins_home/workspace/_repos_my-repo_master@​libs/c123456789101112131415 # timeout=10
Fetching upstream changes from https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git
</span> > git --version # timeout=10
 > git --version # <span class="code-quote">'git version 2.30.2'</span>
using GIT_ASKPASS to set credentials 
 > git fetch --no-tags --force --progress -- https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git +refs/heads/*:refs/remotes/origin/* # timeout=10
</span>Aborted by BLABLA
ERROR: Checkout failed
java.lang.NullPointerException
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2702)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2111)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:87)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:623)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:852)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1229)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1312)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
    at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.lambda$doRetrieve$1(SCMSourceRetriever.java:201)
    at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrySCMOperation(SCMSourceRetriever.java:148)
    at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.doRetrieve(SCMSourceRetriever.java:200)
    at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrieve(SCMSourceRetriever.java:137)
    at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:260)
    at org.jenkinsci.plugins.workflow.libs.LibraryStep$Execution.run(LibraryStep.java:229)
    at org.jenkinsci.plugins.workflow.libs.LibraryStep$Execution.run(LibraryStep.java:157)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
    at hudson.security.ACL.impersonate2(ACL.java:451)
    at hudson.security.ACL.impersonate(ACL.java:463)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:829)
Retrying after 10 seconds
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential my-token
Wiping out workspace first.
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git </span></pre>
<p> </p>

<p> </p>

<p> </p>

<p><b>How to reproduce</b></p>

<p>Create new jenkins pipeline that has scm checkout step (enabled by default) & has shared libs in it</p>

<p>Go to Configure System --> and increase SCM checkout retry count to 2</p>

<p><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/59280/59280_image-2022-10-17-13-56-56-055.png" style="border: 0px solid black" /></span></p>

<p>Then, try to <b>abort</b> the job while it performing scm checkout</p>

<p> </p>

<p>Note: I wasn't sure if this is related to the git plugin or to pipeline scm step plugin, sorry if I got it wrong</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dordor">dordor</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-69875" target="_blank">Feature: abort job while performing scm checkout cause retry instead of aborting it</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: git-client-plugin, git-plugin, scm-api-plugin
<li><b>label(s)</b>: checkout, git, git-client, git-plugin, scm
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-12-02
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>If you increase  SCM checkout retry, and you abort a job while it performing scm checkout, it will not detect that the job has been aborted and it will <b>retry</b> the job instead of <b>aborting</b> it. see log:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Started by user BLABLA
Obtained Jenkinsfile from c123456789101112131415
[Pipeline] Start of Pipeline
[Pipeline] library
Loading library pipeline-library@master
Attempting to resolve my-branch from remote references...
 &gt; git --version # timeout=10
 &gt; git --version # <span class="code-quote">'git version 2.30.2'</span>
using GIT_ASKPASS to set credentials 
 &gt; git ls-remote -h -- https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git # timeout=10
</span>Found match: refs/heads/my-branch revision 164e4f446c6fb83a07a71f6f657c3ec1b5c35779
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential my-token
Wiping out workspace first.
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git
</span> &gt; git init /<span class="code-keyword">var</span>/jenkins_home/workspace/_repos_my-repo_master@libs/c123456789101112131415 # timeout=10
Fetching upstream changes from https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git
</span> &gt; git --version # timeout=10
 &gt; git --version # <span class="code-quote">'git version 2.30.2'</span>
using GIT_ASKPASS to set credentials 
 &gt; git fetch --no-tags --force --progress -- https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git +refs/heads/*:refs/remotes/origin/* # timeout=10
</span>Aborted by BLABLA
ERROR: Checkout failed
java.lang.NullPointerException
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2702)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2111)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:87)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:623)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:852)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1229)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1312)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
    at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.lambda$doRetrieve$1(SCMSourceRetriever.java:201)
    at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrySCMOperation(SCMSourceRetriever.java:148)
    at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.doRetrieve(SCMSourceRetriever.java:200)
    at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrieve(SCMSourceRetriever.java:137)
    at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:260)
    at org.jenkinsci.plugins.workflow.libs.LibraryStep$Execution.run(LibraryStep.java:229)
    at org.jenkinsci.plugins.workflow.libs.LibraryStep$Execution.run(LibraryStep.java:157)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
    at hudson.security.ACL.impersonate2(ACL.java:451)
    at hudson.security.ACL.impersonate(ACL.java:463)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:829)
Retrying after 10 seconds
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential my-token
Wiping out workspace first.
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https:<span class="code-comment">//bitbucket.org/account_name/repo_name.git </span></pre>
</div></div>
<p> </p>

<p> </p>

<p> </p>

<p><b>How to reproduce</b></p>

<p>Create new jenkins pipeline that has scm checkout step (enabled by default) &amp; has shared libs in it</p>

<p>Go to Configure System --&gt; and increase SCM checkout retry count to 2</p>

<p><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/59280/59280_image-2022-10-17-13-56-56-055.png" style="border: 0px solid black" /></span></p>

<p>Then, try to <b>abort</b> the job while it performing scm checkout</p>

<p> </p>

<p>Note: I wasn't sure if this is related to the git plugin or to pipeline scm step plugin, sorry if I got it wrong</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.361.2<br/>
Git client plugin 3.12.1<br/>
Git plugin 4.12.1<br/>
Pipeline: SCM Step 400.v6b_89a_1317c9a_<br/>
SCM API Plugin 621.vda_a_b_055e58f7
```
</details>
<details><summary><i>1 attachment</i></summary>

- [image-2022-10-17-13-56-56-055.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/59280/image-2022-10-17-13-56-56-055.png)
  > ![image-2022-10-17-13-56-56-055.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/59280/image-2022-10-17-13-56-56-055.png)
</details>

**Comment by Itz-bhavii** [comment]
I’d like to work on this issue.

From the stack trace, it appears that when a build is aborted during SCM checkout, the abort or interrupt is not being detected before the Git Plugin proceeds with the checkout flow, which leads to a NullPointerException and a subsequent retry.

I plan to focus on improving abort handling within the git-plugin checkout path, so that aborted builds fail fast and do not continue into retry logic from the Git Plugin side. This will also ensure the abort path is handled cleanly to avoid the observed NPE.

I’ll start by examining GitSCM.checkout and related abort/interrupt handling in the Git Plugin.
